Set-Location "$PSScriptRoot\..\docs"
New-Item -ItemType Directory -Force -Path 'archive\reports','archive\fixes','archive\superseded' | Out-Null

function Move-IfExists([string]$name, [string]$destDir) {
    if (Test-Path -LiteralPath $name) {
        Move-Item -LiteralPath $name -Destination (Join-Path $destDir $name) -Force
        return 1
    }
    return 0
}

$m = 0

$reports = @(
    'INTEGRATION_SUMMARY.md','SYSTEM_INTEGRATION_SUMMARY.md','CONVERTER_UPDATES_SUMMARY.md',
    'PANEL_CLEANUP_SUMMARY.md','GENERATOR_ENHANCEMENT_SUMMARY.md',
    'COMPLETE_BUILDING_GENERATION_SYSTEM.md','COMPLETE_PLAN_TO_3D_PIPELINE.md',
    'COMPLETE_SYSTEM_INTEGRATION_REPORT.md','COMPLETE_SYSTEM_IMPLEMENTATION_PLAN.md',
    'COMPLETE_ROOF_SYSTEM_V2.md','PLAN_TO_SKELETON_COMPLETE_SYSTEM.md',
    'PATH_DRIVEN_GENERATION_COMPLETE.md','COMPONENT_ASSEMBLER_COMPLETE.md',
    'BUILDING_MASS_ASSEMBLY_COMPLETE.md','UNUSED_CLASSES_INTEGRATION_COMPLETE.md',
    'FINAL_INTEGRATION_STATUS.md','FinalSystemIntegrationReport.md',
    'SYSTEM_INTEGRATION_COMPLETE.md','SystemIntegrationComplete.md',
    'SYSTEM_INTEGRATION_CHECK.md','SYSTEM_STATUS_REPORT.md',
    'PHASE1_TOOLTIP_COMPLETE.md','PHASE2_SELECTION_TOOL_PROGRESS.md',
    'PHASE3_SEMANTIC_SYSTEM_COMPLETE.md','SKELETON_PATCH_PIPELINE_STATUS.md',
    'GENERATION_ISSUES_ANALYSIS.md','REFACTORING_PLAN_ARCHITECTURE_CALIBRATION.md',
    'PLAN_PROGRAM_COMPILER_INTEGRATION.md','SKELETON_GENERATOR_ENHANCEMENTS.md',
    'SKELETON_TYPE_REFINEMENT.md','COMPONENT_TOOL_IMPROVEMENTS.md',
    'FINAL_UNUSED_CLASSES_INTEGRATION.md','UNUSED_CLASSES_INTEGRATION.md'
)

$fixes = @(
    'BOX_SELECT_REALTIME_UPDATE_FIX.md','FIX_BUILDING_DETAILS_ISSUE.md',
    'THUMBNAIL_HIGH_RESOLUTION_FIX.md','THUMBNAIL_ROLLBACK_FIX.md',
    'BUG_FIX_LLMPLAN_ROUTING.md','FIX_MISSING_COMPONENT_GENERATORS.md',
    'GENERATOR_FEATURE_MATCHING_FIX.md','DIRECTION_ARROW_RENDERING_FIX.md',
    'THUMBNAIL_FIX_ANCHOR_REQUIRED.md','SELECTION_PREVIEW_FIX.md',
    'FIX_STYLE_FROM_FEATURES.md','THUMBNAIL_DISPLAY_FIX.md',
    'THUMBNAIL_MAXIMIZED_SEAMLESS_FIX.md','THUMBNAIL_ENHANCED_RENDERING.md',
    'THUMBNAIL_RENDER_IMPROVEMENTS.md','THUMBNAIL_DEBUG_VERSION.md',
    'THUMBNAIL_DEBUG_GUIDE.md','ATTACHMENT_MODE_NAMING_IMPROVEMENT.md'
)

$superseded = @(
    'ROOF_PLATE_V1.md','ROOF_PLATE_V2.md','ROOF_COMPONENT_ASSEMBLY_V2.md',
    'ROOF_COMPONENT_ASSEMBLY_COMPLETE.md','ComponentQueryRankingSystemV2.md',
    'GENERATOR_SYSTEMS_USAGE_ANALYSIS.md','GENERATOR_SYSTEMS_INTEGRATION_ANALYSIS.md',
    'GENERATOR_SYSTEMS_COMPARISON.md','GENERATOR_SYSTEMS_CONFLICT_ANALYSIS.md',
    'BUILDING_MASS_ASSEMBLY_ARCHITECTURE.md','BUILDING_MASS_ASSEMBLY_IMPLEMENTATION.md',
    'BUILDING_MASS_ASSEMBLY_PHASE2.md','BUILDING_MASS_ASSEMBLY_PHASE3.md',
    'BUILDING_MASS_MVP.md','BUILDING_MASS_MVP_IMPLEMENTATION.md',
    'BUILDING_MASS_TO_SKELETON_DERIVATION.md','BUILDING_MASS_TO_SOCKET_COMPLETE.md',
    'BUILDING_MASS_COMPOSITION_PATTERNS.md','BUILDING_MASS_VS_MASSDEFINITION.md',
    'BUILDING_MASS_SYSTEM_INTEGRATION.md','COMPONENT_ASSEMBLER_IMPLEMENTATION.md',
    'COMPONENT_ASSEMBLER_IMPROVEMENTS.md','COMPONENT_ASSEMBLER_EVALUATION.md',
    'COMPONENT_ASSEMBLER_USAGE.md','ComponentPlanCompilerImplementation.md',
    'DYNAMIC_STYLE_SYSTEM_IMPLEMENTATION.md','SMART_GENERATOR_ROUTING_SOLUTION.md'
)

foreach ($f in $reports) { $m += Move-IfExists $f 'archive\reports' }
foreach ($f in $fixes) { $m += Move-IfExists $f 'archive\fixes' }
foreach ($f in $superseded) { $m += Move-IfExists $f 'archive\superseded' }

Write-Host "Moved $m files"
