package com.formacraft.client.tool;

import com.formacraft.common.component.health.HealthCheckResult;
import com.formacraft.common.component.placement.AttachmentType;
import com.formacraft.common.component.transform.Mirror;
import com.formacraft.client.ui.panel.DirectionalityMode;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Direction;
import net.minecraft.util.math.Vec3d;

import java.util.HashSet;
import java.util.Set;

/**
 * 捕获态草案：用于隔离“拾取过程中的状态”和“最终定义状态”。
 */
public class ComponentCaptureDraft {
    public DraftPhase phase = DraftPhase.EMPTY;
    public boolean dirty = false;

    public final SelectionDraft selection = new SelectionDraft();
    public final HostDraft host = new HostDraft();
    public final AnchorDraft anchor = new AnchorDraft();
    public final OrientationDraft orientation = new OrientationDraft();
    public final ConnectorDraft connectors = new ConnectorDraft();

    public HealthCheckResult lastHealth = null;
    public ComponentCaptureDraft snapshotBeforeAutoFix = null;
    public java.util.List<String> lastAutoFixReport = null;

    public enum DraftPhase {
        EMPTY,
        SELECTION_DEFINED,
        HOST_DEFINED,
        ANCHOR_DEFINED,
        ORIENTATION_DEFINED,
        READY
    }

    public enum AnchorSnapKind {
        FREE,
        CORNER,
        EDGE_MID,
        FACE_CENTER,
        CENTER
    }

    public static class SelectionDraft {
        public boolean explicit = false;
        public Set<BlockPos> blocks = null;
        public BlockPos aabbMin = null;
        public BlockPos aabbMax = null;

        public void updateAabbFromBlocks() {
            if (blocks == null || blocks.isEmpty()) {
                aabbMin = null;
                aabbMax = null;
                return;
            }
            BlockPos min = null;
            BlockPos max = null;
            for (BlockPos p : blocks) {
                if (min == null) {
                    min = p;
                    max = p;
                } else {
                    min = new BlockPos(
                            Math.min(min.getX(), p.getX()),
                            Math.min(min.getY(), p.getY()),
                            Math.min(min.getZ(), p.getZ())
                    );
                    max = new BlockPos(
                            Math.max(max.getX(), p.getX()),
                            Math.max(max.getY(), p.getY()),
                            Math.max(max.getZ(), p.getZ())
                    );
                }
            }
            aabbMin = min;
            aabbMax = max;
        }
    }

    public static class HostDraft {
        public AttachmentType attachment = AttachmentType.NONE;
        public BlockPos referenceBlock = null;
        public Direction normal = null;
        public boolean allowAirHost = false;
        public float planeOffset = 0.0f;
        public boolean confirmed = false;
    }

    public static class AnchorDraft {
        public BlockPos worldPos = null;
        public Vec3d localNormalized = null;
        public AnchorSnapKind snapKind = AnchorSnapKind.FREE;
        public boolean allowOutsideSelection = false;
        public boolean confirmed = false;
    }

    public static class OrientationDraft {
        public DirectionalityMode mode = DirectionalityMode.NONE;
        public Direction facing = Direction.SOUTH;
        public Mirror mirror = Mirror.NONE;
        public boolean hasInteriorExterior = false;
        public boolean hasBottomTop = false;
        public BlockPos insideMarkWorld = null;
        public BlockPos outsideMarkWorld = null;
        public BlockPos bottomMarkWorld = null;
        public BlockPos topMarkWorld = null;
        public boolean confirmed = false;
    }

    public static class ConnectorDraft {
        public boolean autoGenerated = false;
        public boolean confirmed = false;
    }

    public void loadFrom(ComponentToolState state) {
        if (state == null) return;
        selection.blocks = state.explicitSelectedBlocks != null
                ? new HashSet<>(state.explicitSelectedBlocks)
                : null;
        selection.explicit = state.useExplicitSelection;
        selection.aabbMin = null;
        selection.aabbMax = null;
        if (selection.explicit) {
            selection.updateAabbFromBlocks();
        }

        anchor.worldPos = state.anchorWorld;
        anchor.allowOutsideSelection = state.allowAnchorOutsideSelection;

        host.attachment = state.attachmentMode;
        host.referenceBlock = state.hostFaceBlock;
        host.normal = state.hostFaceNormal;

        orientation.facing = state.facing;
        orientation.mirror = state.mirror;
        orientation.hasInteriorExterior = state.hasInteriorExterior;
        orientation.hasBottomTop = state.hasBottomTop;
        if (orientation.hasInteriorExterior && orientation.hasBottomTop) {
            orientation.mode = DirectionalityMode.BOTH;
        } else if (orientation.hasInteriorExterior) {
            orientation.mode = DirectionalityMode.INSIDE_OUTSIDE;
        } else if (orientation.hasBottomTop) {
            orientation.mode = DirectionalityMode.BOTTOM_TOP;
        } else {
            orientation.mode = DirectionalityMode.NONE;
        }
        orientation.insideMarkWorld = state.insideMarkWorld;
        orientation.outsideMarkWorld = state.outsideMarkWorld;
        orientation.bottomMarkWorld = state.bottomMarkWorld;
        orientation.topMarkWorld = state.topMarkWorld;
    }

    public void applyTo(ComponentToolState state) {
        if (state == null) return;
        state.explicitSelectedBlocks = selection.blocks != null
                ? new HashSet<>(selection.blocks)
                : null;
        state.useExplicitSelection = selection.explicit;
        state.anchorWorld = anchor.worldPos;
        state.allowAnchorOutsideSelection = anchor.allowOutsideSelection;
        state.attachmentMode = host.attachment;
        state.hostFaceBlock = host.referenceBlock;
        state.hostFaceNormal = host.normal;
        state.facing = orientation.facing;
        state.mirror = orientation.mirror;
        state.hasInteriorExterior = orientation.hasInteriorExterior;
        state.hasBottomTop = orientation.hasBottomTop;
        state.insideMarkWorld = orientation.insideMarkWorld;
        state.outsideMarkWorld = orientation.outsideMarkWorld;
        state.bottomMarkWorld = orientation.bottomMarkWorld;
        state.topMarkWorld = orientation.topMarkWorld;
    }

    public boolean hasExplicitSelection() {
        return selection.explicit && selection.blocks != null && !selection.blocks.isEmpty();
    }

    public void updatePhase() {
        boolean hasSelection = selection.explicit
                ? (selection.blocks != null && !selection.blocks.isEmpty())
                : (selection.aabbMin != null && selection.aabbMax != null);
        if (!hasSelection) {
            phase = DraftPhase.EMPTY;
            return;
        }
        if (host.referenceBlock != null && host.normal != null) {
            phase = DraftPhase.HOST_DEFINED;
        } else {
            phase = DraftPhase.SELECTION_DEFINED;
        }
        if (anchor.worldPos != null) {
            phase = DraftPhase.ANCHOR_DEFINED;
        }
        if (orientation.hasInteriorExterior || orientation.hasBottomTop) {
            phase = DraftPhase.ORIENTATION_DEFINED;
        }
    }

    public ComponentCaptureDraft copy() {
        ComponentCaptureDraft out = new ComponentCaptureDraft();
        out.phase = this.phase;
        out.dirty = this.dirty;

        out.selection.explicit = this.selection.explicit;
        out.selection.blocks = this.selection.blocks != null ? new HashSet<>(this.selection.blocks) : null;
        out.selection.aabbMin = this.selection.aabbMin;
        out.selection.aabbMax = this.selection.aabbMax;

        out.host.attachment = this.host.attachment;
        out.host.referenceBlock = this.host.referenceBlock;
        out.host.normal = this.host.normal;
        out.host.allowAirHost = this.host.allowAirHost;
        out.host.planeOffset = this.host.planeOffset;
        out.host.confirmed = this.host.confirmed;

        out.anchor.worldPos = this.anchor.worldPos;
        out.anchor.localNormalized = this.anchor.localNormalized;
        out.anchor.snapKind = this.anchor.snapKind;
        out.anchor.allowOutsideSelection = this.anchor.allowOutsideSelection;
        out.anchor.confirmed = this.anchor.confirmed;

        out.orientation.mode = this.orientation.mode;
        out.orientation.facing = this.orientation.facing;
        out.orientation.mirror = this.orientation.mirror;
        out.orientation.hasInteriorExterior = this.orientation.hasInteriorExterior;
        out.orientation.hasBottomTop = this.orientation.hasBottomTop;
        out.orientation.insideMarkWorld = this.orientation.insideMarkWorld;
        out.orientation.outsideMarkWorld = this.orientation.outsideMarkWorld;
        out.orientation.bottomMarkWorld = this.orientation.bottomMarkWorld;
        out.orientation.topMarkWorld = this.orientation.topMarkWorld;
        out.orientation.confirmed = this.orientation.confirmed;

        out.connectors.autoGenerated = this.connectors.autoGenerated;
        out.connectors.confirmed = this.connectors.confirmed;

        out.lastHealth = this.lastHealth;
        out.snapshotBeforeAutoFix = this.snapshotBeforeAutoFix;
        out.lastAutoFixReport = this.lastAutoFixReport != null ? new java.util.ArrayList<>(this.lastAutoFixReport) : null;
        return out;
    }

    public void copyFrom(ComponentCaptureDraft other) {
        if (other == null) return;
        ComponentCaptureDraft tmp = other.copy();
        this.phase = tmp.phase;
        this.dirty = tmp.dirty;

        this.selection.explicit = tmp.selection.explicit;
        this.selection.blocks = tmp.selection.blocks;
        this.selection.aabbMin = tmp.selection.aabbMin;
        this.selection.aabbMax = tmp.selection.aabbMax;

        this.host.attachment = tmp.host.attachment;
        this.host.referenceBlock = tmp.host.referenceBlock;
        this.host.normal = tmp.host.normal;
        this.host.allowAirHost = tmp.host.allowAirHost;
        this.host.planeOffset = tmp.host.planeOffset;
        this.host.confirmed = tmp.host.confirmed;

        this.anchor.worldPos = tmp.anchor.worldPos;
        this.anchor.localNormalized = tmp.anchor.localNormalized;
        this.anchor.snapKind = tmp.anchor.snapKind;
        this.anchor.allowOutsideSelection = tmp.anchor.allowOutsideSelection;
        this.anchor.confirmed = tmp.anchor.confirmed;

        this.orientation.mode = tmp.orientation.mode;
        this.orientation.facing = tmp.orientation.facing;
        this.orientation.mirror = tmp.orientation.mirror;
        this.orientation.hasInteriorExterior = tmp.orientation.hasInteriorExterior;
        this.orientation.hasBottomTop = tmp.orientation.hasBottomTop;
        this.orientation.insideMarkWorld = tmp.orientation.insideMarkWorld;
        this.orientation.outsideMarkWorld = tmp.orientation.outsideMarkWorld;
        this.orientation.bottomMarkWorld = tmp.orientation.bottomMarkWorld;
        this.orientation.topMarkWorld = tmp.orientation.topMarkWorld;
        this.orientation.confirmed = tmp.orientation.confirmed;

        this.connectors.autoGenerated = tmp.connectors.autoGenerated;
        this.connectors.confirmed = tmp.connectors.confirmed;

        this.lastHealth = tmp.lastHealth;
        this.snapshotBeforeAutoFix = tmp.snapshotBeforeAutoFix;
        this.lastAutoFixReport = tmp.lastAutoFixReport;
    }
}
